
version: '3.8'

services:
  urlshortener:
    build:
      context: .
    environment:
      - NODE_ENV=development
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    env_file: .env
    command: ['npm', 'run', 'dev']
